### ISSUE TITLE
Incorrect AMPLITUDE_API_HOST, current one is deperecated

### ISSUE THREAD

**Issue by jeetkr** [amplitude/Amplitude-Node#11]
Instead of:
export const AMPLITUDE_API_HOST = 'api.amplitude.com'
it should be export const AMPLITUDE_API_HOST = 'api2.amplitude.com'
Right now this throws an error:
 [Amplitude|Error] Event is not submitted. { Error: certificate has expired
 at TLSSocket.onConnectSecure (_tls_wrap.js:1041:34)
 at TLSSocket.emit (events.js:160:13)
 at TLSSocket._finishInit (_tls_wrap.js:638:8) code: 'CERT_HAS_EXPIRED' }

**Comment by haoliu-amp** [comment]
For now, as a temporary solution.
https://github.com/amplitude/Amplitude-Node/releases/tag/v0.3.3

Thanks @timsu

**Comment by haoliu-amp** [comment]
Going to keep this issue open until we have a complete solution with our CA Root Certificate issue.

**Comment by haoliu-amp** [comment]
Ok, api.amplitude.com endpoint should be ok to use now.
