### ISSUE TITLE
Using @amplitude/identify to set boolean user property doesn't work

### ISSUE THREAD

**Issue by ajin12** [amplitude/Amplitude-Node#116]
## Expected Behavior

Tried to set a user property to `true`/`false`

## Current Behavior

Boolean user property didn't get set in Amplitude using `@amplitude/identify` library. As a workaround, I've been casting to `string` first before calling `amplitudeClient.identify()`.

## Steps to Reproduce

Tried doing something like:
```
const identify = new Identify();
identify.set("someProperty", true);
amplitudeClient.identify(userId, deviceId, identify);
```
to set `someProperty` user property to `true` but it didn't get set.

As a workaround, am currently doing:
```
const identify = new Identify();
identify.set("someProperty", String(true));
amplitudeClient.identify(userId, deviceId, identify);
```
to get it set.

## Environment
- SDK Version:  1.5.3 (@amplitude/identify: 1.5.5)
- Node version:  v14.8.0

**Comment by yuhao900914** [comment]
@ajin12  Thanks for pointing that out. The boolean type is not our valid type for Node SDK, but we should include that.  Will plan to work on that.

**Comment by ajin12** [comment]
> @ajin12 Thanks for pointing that out. The boolean type is not our valid type for Node SDK, but we should include that. Will plan to work on that.

Thanks!
