### ISSUE TITLE
New User event not visible after first batch event sent

### ISSUE THREAD

**Issue by macci10** [amplitude/Amplitude-Node#121]
## Summary
I used Batch API to send an event with event_type = "track" and self generated device_id. "track" event is visible in Amplitude. But "New User" is not created itself as according to my understanding is created by default when a user is created in amplitude. I created users with Identity API with some user_properties.

**Comment by ajhorst** [comment]
@macci10 does the event "track" only appear for a single user ID in amplitude? And are you generating the device_ids yourself or letting the SDK generate them?

**Comment by ajhorst** [comment]
@macci10 any update on this one?

**Comment by macci10** [comment]
I have found that I was querying the users in the wrong way. New User event
was being created when I call batch api. So there was no issue. Thanks for
your time.

**Comment by ajhorst** [comment]
@macci10 glad to hear that you figured it out
