### ISSUE TITLE
Feature Request - Add identify to the SDK

### ISSUE THREAD

**Issue by axelvaindal** [amplitude/Amplitude-Node#13]
Hello,

We are currently using the Identify API to store users related information.
Although it works well, we are also trying to use the Node SDK to `logEvent`.
It would be nice to add identify API support to the SDK, so we could use it to do both event logging and user identifying.

Thanks a lot,

**Comment by kelvin-lu** [comment]
Hi @axelvaindal, this is on our roadmap and we're looking forward to adding it to our Node SDK!

**Comment by StErMi** [comment]
is there an update about the release date of the Identify API?

**Comment by kelvin-lu** [comment]
@StErMi We will have plans on planning/working on this in the coming month! And will keep you updated.

**Comment by fiteco** [comment]
Hi, any news on this implementation?

**Comment by kelvin-lu** [comment]
@fiteco this is next-in-priority for the Node SDK after adding additional testing to the more complicated utilities. Apologies for the delay, but hoping to get to this soon/ in the next week.

If you happen to get to it before us, I'd be happy to help and review!

**Comment by Farmijo** [comment]
Hi! Any news about the status of this?

**Comment by ZoharBergman** [comment]
> Hi! Any news about the status of this?

Any news?

**Comment by kelvin-lu** [comment]
this has been added in v1.3.1 - thank you all and apologies for the continued delays on this project!
