### ISSUE TITLE
requestTimeoutMillis breaks 1.8.0 -> 1.8.1

### ISSUE THREAD

**Issue by Akkuma** [amplitude/Amplitude-Node#136]
## Expected Behavior
Upgrade to 1.8.1 from 1.8.0 shouldn't introduce build failures

## Current Behavior
Upgrading from 1.8.1 requires setting `requestTimeoutMillis` now 

## Possible Solution
`requestTimeoutMillis` should be optional defaulting to the constant, which appears unused

## Steps to Reproduce
Write some code that compiles for 1.8.0 th

## Environment
- SDK Version: 1.8.1
- Node version: N/A

**Comment by ajhorst** [comment]
@Akkuma can you give more details about your dev environment? I'm not able to reproduce it in mine. Are you creating your own transport or retry class for the SDK, possibly?

**Comment by Akkuma** [comment]
> @Akkuma can you give more details about your dev environment? I'm not able to reproduce it in mine. Are you creating your own transport or retry class for the SDK, possibly?

Yes, we're directly creating our own Retry class and using `HTTPTransport`, which is where the error arises. The default used to be baked into `HTTPTransport` and now it is required to be passed in.

**Comment by ajhorst** [comment]
@Akkuma gotcha, I'll get a fix out later today

**Comment by Akkuma** [comment]
> @Akkuma gotcha, I'll get a fix out later today

Thanks for the quick responses. I worked around this by just leveraging the `DEFAULT_OPTIONS` inside of the package. It would be nice to expose them from the top too.
