### ISSUE TITLE
How should I generate the device ID ?

### ISSUE THREAD

**Issue by babyken** [amplitude/Amplitude-Node#139]
## Generate device ID for anonymous

I am using nuxtjs with the amplitude-node package. I would like to know how do I let amplitude auto generate device ID for anonymous user.(non-logged in user)

Thank you

**Comment by dantetam** [comment]
Hello @babyken ,

The Node SDK by default generates a base 36 ID for all users, if a device ID is not passed in.

See the [source code](https://github.com/amplitude/Amplitude-Node/blob/46fced588f3a644993cc693501ee8755c8a6d89a/packages/identity/src/identity.ts#L38).

**Comment by dantetam** [comment]
Let us know if you have more questions.

**Comment by babyken** [comment]
@dantetam Thank you for quick reply. I tried to logEvent without user_id and device_id, the return result is "skipped". Am I missing something ?? any hints where should I look into ?

many thanks

**Comment by haoliu-amp** [comment]
@babyken Sorry about the confusion. Please ignore the previous statement
```The Node SDK by default generates a base 36 ID for all users, if a device ID is not passed in. Base 36 in this context is A-Z and 0-9.```

To correct it - Our Node SDK doesn't help generate a deviceId. 
Note, that code example we provided is NOT for our Node SDK but for others.

Events can come from different devices, so in our backend, we can't assume or even generate which deviceId it has.
What you should do is to generate a random number for your deviceId, you can use the function from [here](https://github.com/amplitude/Amplitude-Node/blob/46fced588f3a644993cc693501ee8755c8a6d89a/packages/utils/src/base36.ts).

**Comment by babyken** [comment]
@haoliu-amp Thank you for clarify. Honestly, I come to this issue because we are using nuxtjs (Server side rendering version of vuejs). We would like to log user action, i.e. all of them should happen on frontend only. I am not sure if I should stick with amplitude-js nor amplitude-node.

Which package is designed for SSR framework like nextjs and nuxtjs?? 
Thank you in advance.

**Comment by ajhorst** [comment]
Hi @babyken, if you would like to track client side behavior with a device ID, you should use the `amplitude-js` SDK instead of this Node SDK. The `amplitude-js` handles identifying users through a client-side cookie that randomly generates and stores a device ID.  

You will need to configure the JS SDK to initialize on the client side, and to send events from client side actions as well.
