### ISSUE TITLE
User properties inheritance

### ISSUE THREAD

**Issue by andreymolchanov** [amplitude/Amplitude-Node#153]
Hi! We use amplitude-node/1.9.0. And send the events using just event_type, user_id and a single user_properties item:
```
await amplitudeClient.logEvent({
    event_type: 'business_subscription_linked',
    user_id: user.id,
    user_properties: {
        business_subscription_account: subscription.accountId
    }
});
```

In some cases the event received contains inherited user properties from the previously sent client events, but often it doesn't — including even standard system properties like Platform, IP or Start Version.

There seems to be no place to fail from our side (it's just too simple), so I suppose it could be an Amplitude bug.

Correct:
![image](https://user-images.githubusercontent.com/3244075/141815931-743acb1e-2b96-49e9-983d-8abbc7bd6cfc.png)

Incorrect:
![image](https://user-images.githubusercontent.com/3244075/141815646-cc4f54d5-121b-47fd-ad6a-a5d95699219a.png)

**Comment by kevinpagtakhan** [comment]
Hi @andreymolchanov! Thanks for submitting an issue. For Node SDK, the `event` parameter passed to `logEvent()` function must explicitly include entries for the user properties you want to associate with the event; otherwise it will show as empty like the second screenshots.

**Comment by andreymolchanov** [comment]
@kevinpagtakhan thank you for the answer. It doesn't seem like the best solution — taking into account the inheritance nature of user properties. Is there a way not to send neither empty nor any specific values so the properties in Amplitude would just be inherited from the previously sent?

**Comment by kevinpagtakhan** [comment]
@andreymolchanov unfortunately, we do not support this kind of inheritance since events sent can come from multiple users/devices at overlapping times

**Comment by andreymolchanov** [comment]
It's up to you in the end but if we use plain HTTP Api without the Node client, it would work exactly like this, with [the inheritance](https://help.amplitude.com/hc/en-us/articles/115002380567-User-properties-and-event-properties#h_856d23e3-10ea-4398-a50d-4982a42d1f3f). And there're even [Disable tracking](https://developers.amplitude.com/docs/ios#disable-tracking) methods in iOS SDK. But it's difficult to argue with the only person supporting this SDK. :(

**Comment by kevinpagtakhan** [comment]
It works differently for client side SDKs like iOS and [web](https://github.com/amplitude/Amplitude-JavaScript). These will attempt to track those metadata by default. The server side SDKs work differently as they are meant to run on proxy service, sitting in between your client app (web/mobile app) and amplitude service. The amplitude instance on the Node SDK can forward requests coming from multiple users and devices, as opposed to client side SDKs where the amplitude instance is running for a specific user and device.

**Comment by andreymolchanov** [comment]
I see your logic but an option not to set any values so they are inherited from the previous event wouldn't harm.
