### ISSUE TITLE
Where can I see the event log in amplitude?

### ISSUE THREAD

**Issue by diegosv2000** [amplitude/Amplitude-Node#169]
I created a function for logging events in amplitude, the response I get is
`
{
  status: 'success',
  statusCode: 200,
  body: {
    eventsIngested: 2,
    payloadSizeBytes: 539,
    serverUploadTime: 1654620336284
  }
}
`
But when entering the Amplitued dashboard, I can't find it

**Comment by justin-fiedler** [comment]
Hi @diegosv2000 currently the Node SDK logs to the console only. 
https://github.com/amplitude/Amplitude-Node/blob/main/packages/utils/src/logger.ts#L35

If you would like add custom logging you can do so with a custom Middleware as described here.
https://github.com/amplitude/Amplitude-Node/blob/main/packages/utils/src/logger.ts#L35

Hope this helps!
