### ISSUE TITLE
Can we send batch/bulk events at once

### ISSUE THREAD

**Issue by astar10239** [amplitude/Amplitude-Node#170]
Hi,

I am looking to integrate the node js sdk and want to push bulk/batch events async,

Is there a function to do that ?

**Comment by kevinpagtakhan** [comment]
Hi @astar10239, thanks for submitting a question. This is possible, not through a function but a configuration. To do this, initialize amplitude client with the `uploadIntervalInSec` configuration.

```ts
Amplitude.init(<API_KEY>, {
  uploadIntervalInSec: 10,
);
```

The example configuration above allows amplitude client to send in 10 second intervals, allowing for bulk/batch event payload.
