### ISSUE TITLE
How to track revenue?

### ISSUE THREAD

**Issue by alexblack** [amplitude/Amplitude-Node#181]
I'm looking to track revenue to Amplitude, so that it shows up in reports of type `Revenue LTV`.  I read here: https://help.amplitude.com/hc/en-us/articles/115003116888-Track-revenue

Do we simply need to specify these properties in `logEvent`? like this:

```
amplitude.logEvent({ 
  user_id,
  revenue: 100,
});
```

When I do this I do see the `$revenue` property on the event in amplitude, but i see $0 revenue in the `Revenue LTV` report

**Comment by yuhao900914** [comment]
Hi @alexblack, 
The event_types is required in the logEvent. And the event_type for revenue is ``. 
Can you try 
```
amplitude.logEvent({ 
 event_type:  "revenue_amount"
  user_id,
  revenue: 100,
});
```

**Comment by alexblack** [comment]
Thanks for the response.  It turns out it was working fine, I just had the
wrong expectations about how/when it'd show up in Amplitude.

(I was setting event_type, I had left it out of the code snippet)

**Comment by yuhao900914** [comment]
Closing this issue since it works fine. Feel free to re-open or create another issue if you need other help. Thanks.
