### ISSUE TITLE
v1.0.0 is empty

### ISSUE THREAD

**Issue by agoldis** [amplitude/Amplitude-Node#39]
## Expected Behavior
npm module should contain ... the module 

## Current Behavior
there's no code in the module

## Possible Solution
release the code together with the module

## Steps to Reproduce
```sh
$ yarn add @amplitude/node
$ cd node_modules/@amplitude/node
$ cat package.json | grep index
  "main": "dist/index.js",
  "module": "esm/index.js",
  "types": "dist/index.d.ts",
$ ls dist/index.js esm/index.js dist/index.d.ts
ls: dist/index.d.ts: No such file or directory
ls: dist/index.js: No such file or directory
ls: esm/index.js: No such file or directory
```

## Environment
- SDK Version: 1.0.0
- Node version: v10.22.1

**Comment by kelvin-lu** [comment]
Hi @agoldis ! thanks for flagging. We've identified this as an issue with a recent compilation change. We're looking to release a minor patch soon :)

**Comment by agoldis** [comment]
That was quick... Good luck!

**Comment by ZoharBergman** [comment]
Hi @kelvin-lu, I see that you merged a fix but the `types` and `utils` packages are still missing
![image](https://user-images.githubusercontent.com/22134554/94808319-a67ecd00-03f9-11eb-8339-fb26a23bf2b2.png)

**Comment by kelvin-lu** [comment]
Hi @ZoharBergman !

I deployed a hotfix last night and discovered this as well - we're hoping to get this resolved asap, but while more of our engineers are active. 

Thank you for reaching out and for your patience - we'll update this asap once we have a new patch out.

**Comment by kelvin-lu** [comment]
Apologies for the inconvenience - v1.0.2 is now ready for usage on all @amplitude/node+type+utils.
