### ISSUE TITLE
Events logged are not appearing in amplitude 

### ISSUE THREAD

**Issue by jkumaranc** [amplitude/Amplitude-Node#59]
## Summary

Hi there,

When I call the log event function from this module, I get the 200 response. But the number of 'eventsIngested' returns 0. And I am not able to see the events in the dashboard either.

`{
      status: 'success',
      statusCode: 200,
      body: {
                 eventsIngested: 0,
                 payloadSizeBytes: 58,
                 serverUploadTime: 1605483387446
      }
  }`

The event was as simple as just this 
`{event_type: 'test'}`

What would be the issue? Appreciate your help guys. Thanks.

**Comment by jkumaranc** [comment]
Figured out I had to either add device_id or user_id in the event. Closing the issue.

**Comment by kelvin-lu** [comment]
@jkumaranc Thanks also for logging this - I created a short PR to make this easier to debug.

There was an assumption made in one layer of the node client that threw away events without one or the other. Now this should appear in debug logs and also return a response with status `'skipped'` to make it more obvious what is happening.

Apologies for the confusion!
