### ISSUE TITLE
Is it possible to set `min_id_length`?

### ISSUE THREAD

**Issue by tom-james-watson** [amplitude/Amplitude-Node#64]
In the documentation for the HTTP API, https://developers.amplitude.com/docs/http-api-v2#properties-2
, a `min_id_length` is mentioned that allows overriding the check that `user_id` must be at least 5 chars long:

>  Validation on user_id length (must be 5 or more characters unless overrided with min_id_length)

I have some user ids which are < 5 chars and am getting `400` responses when sending events. Is there any way to set this `min_id_length` if using the node SDK? It doesn't seem possible from looking at the codebase.

**Comment by jooohhn** [comment]
We'll add an option for this, but something to note is that short ids are often associated with instrumentation issues

**Comment by kelsonpw** [comment]
@tom-james-watson we will be releasing this behavior this week.  you will be able to pass `minIdLength: number` in your options object when calling init.

**Comment by KazankovMarch** [comment]
@jooohhn  could you please explain, what do you mean by "instrumentation issues"?  I have a numeric user_id and I wonder should I add leading zeros to ids below 10000, or just set `min_id_length` option

**Comment by bjornbos** [comment]
@jooohhn Could you please provide an answer to this question of why shorter ids would lead to "instrumentation issues"?
