### ISSUE TITLE
How to set user props?

### ISSUE THREAD

**Issue by arthabus** [amplitude/Amplitude-Node#65]
## Summary

Hi, how do we set/update user properties using this lib?

It seems like it only has logEvent(), flush() and getOptions() methods - is it possible to update user props at all using this library?

If not, could you point in the right direction on how to accomplish it from server side?

**Comment by kelvin-lu** [comment]
Hi @arthabus ,

Apologies. You can still identify users by sending `$identify` events (and there's a pull request we plan on attending to post-thanksgiving to make it easier to interface with it) - if you send events that follow the [event format in our docs](https://developers.amplitude.com/docs/identify-api)

For example:

```
nodeClient.logEvent({
  event_type: '$identify',
  user_id: 'YOUR_USER_ID',
  device_id: 'YOUR_DEVICE_ID',
  user_properties: {
    $set: { source: 'email' }
  }
})
```

**Comment by arthabus** [comment]
perfect, thanks @kelvin-lu!

**Comment by ngokevin** [comment]
Request to add this to the docs!

**Comment by kelvin-lu** [comment]
great callout! we'll try to get this out soon
