### ISSUE TITLE
No insert_id and other critical properties?

### ISSUE THREAD

**Issue by tommedema** [amplitude/Amplitude-Node#75]
At https://developers.amplitude.com/docs/http-api-v2 it's clearly stated that you highly recommend always passing in a insert_id, yet the sdk does not support this property? It is not part of the typescript typings.

Similarly, lots of properties are missing, e.g. os_name, app_version, etc.

**Comment by kelvin-lu** [comment]
@tommedema,

Thanks for raising this issue. You're totally correct that those types are missing - feel free to open a pr to `@amplitude/types` or we can look into resolving this issue this week; we see this as a great first issue.

**Comment by tommedema** [comment]
Seems like there are a lot of properties missing, and this is more than just a typings issue? We'll be reverting to using the HTTP API again

**Comment by kelvin-lu** [comment]
@tommedema Hi! Could you explain more by what you mean by this being more than just a typings issue - have you run into issues using the Node SDK itself because of the event shape (adding insert id, os name, etc.), outside of type compilation issue?

**Comment by tommedema** [comment]
I haven't been able to try and add more properties since typescript won't compile, so didn't realize you allow for passing in arbitrary event properties. Still, we'd like to deploy today so cannot wait for the typings to be updated.

**Comment by tommedema** [comment]
We'd expect all properties at https://developers.amplitude.com/docs/http-api-v2 to be supported

**Comment by kelvin-lu** [comment]
Right, sorry about the lack of typings - why not cast the event sent into logEvent as `any` for the time being until this is resolved? 

I think the call to use the HTTP API is also valid if the Node SDK is not providing any value here - we wanted to help remove the need to do your own HTTP + Batching + Retrying logic but those can be replicated

**Comment by tommedema** [comment]
Ok -- we will be reverting back to the SDK then. We've never had to use `any` in our codebase so hopefully this can be resolved soon.

**Comment by yuhao900914** [comment]
@tommedema, 
Hi there, we want to give you an update about this issue. 
The issue has been resolved in our most resent node v1.5.0. It includes the types of insert_id and other properties.
Again, thanks for raise the issue up.
