### ISSUE TITLE
identify does not allow for deep objects unlike API

### ISSUE THREAD

**Issue by tommedema** [amplitude/Amplitude-Node#83]
This is another case where the SDK is creating friction and we regret not using the base HTTP API.

Per the documentation at https://developers.amplitude.com/docs/identify-api an identify call can have a user_properties prop that supports deep objects up to 40 levels. Yet the Amplitude-Node Identify implementation [only supports numbers, strings, or arrays thereof](https://github.com/amplitude/Amplitude-Node/blob/b7a3fea372a7b7d3c2bb2404fe7c282c1c2f5425/packages/types/src/identify.ts#L23).

Until a solution is found, is there a way to override the types so that we can move forward? Assuming the sdk passes them directly to the user_properties prop of the underlying HTTP API call?

**Comment by kelvin-lu** [comment]
Hey @tommedema,

We'll be looking to fix this in the near future. In the meantime, you are correct in that the SDK passes them directly to the user_properties prop and you can construct your own `identify` events as well:

```
amplitudeClient.logEvent({
  event_type: '$identify',
  user_properties: {
    $set: deepObj,
  },
  device_id: ...
  user_id: ...
})

**Comment by tommedema** [comment]
@kelvin-lu we are getting this: `WARN	Amplitude Logger [Warn]: On Identify operation  $set :  invalid value type  object . Skipping operation`

when using it like so:

```
const identify = new Identify()

// See https://github.com/amplitude/Amplitude-Node/issues/83 on why we need to type cast to `any` here
identify.set('clearbit', clearbitData as any)

await amplitude.identify(userId, deviceId, identify)
```

is there any way around this while using the identify library?

**Comment by ajin12** [comment]
> Hey @tommedema,
> 
> We'll be looking to fix this in the near future. In the meantime, you are correct in that the SDK passes them directly to the user_properties prop and you can construct your own `identify` events as well:
> 
> ```
> amplitudeClient.logEvent({
>   event_type: '$identify',
>   user_properties: {
>     $set: deepObj,
>   },
>   device_id: ...
>   user_id: ...
> })
> ```

@kelvin-lu Following your suggestion above, I am getting this error: `[Amplitude] Invalid eventType input type. Expected string but received object`. Any ideas how this could be resolved? Sample code snippet:

```
amplitudeInstance.logEvent({
    event_type: "$identify",
    user_properties: {
        $set: {"someProperty": true}
    },
    device_id: amplitudeInstance.options.deviceId,
});
```

Thanks!

**Comment by yuhao900914** [comment]
Hi @tommedema , sorry for the late reply. 
Want to give you an update that the latest version of node, v1.5.3, solved this issue. The identify is able to accept deep objects now. Please try it out.
Will close this issue. 
Thanks.
