### ISSUE TITLE
Getting function not implemented on doing this.client.flush()

### ISSUE THREAD

**Issue by mc-lovin** [amplitude/Amplitude-Node#9]
When I do this.client.flush(), it says that function is not implemented.

Is there a workaround? I want to make sure that all the pending logs are sent to the server before my rest api returns a response.

**Comment by haoliu-amp** [comment]
@mc-lovin Currently, when you do `logEvent`, it will immediately send event. The `flush` api will be implemented soon together with buffering for events.

**Comment by mc-lovin** [comment]
@haoliu-amp thanks, but since there is an network call involved there is no guarantee that it will get finished before the outer process is killed ?

**Comment by mc-lovin** [comment]
would it be better for logEvent to return a promise in that case ?

**Comment by haoliu-amp** [comment]
@mc-lovin Since 
In the future, `logEvent` will add event to the buffer, so promise won't make sense.
However, I will make flush API to return promise.

**Comment by mc-lovin** [comment]
fair enough, closing this now. Thanks!
