### ISSUE TITLE
Make REQUEST_CANCEL_TIMEOUT configurable

### ISSUE THREAD

**Issue by HeeL** [amplitude/Amplitude-Node#94]
## Summary

There is a way to configure a time upon which the request to api is cancelled. At the moment its hardcoded to 10 seconds:
https://github.com/amplitude/Amplitude-Node/blob/main/packages/node/src/transports/http.ts#L25

## Motivations

Make it possible to configure the waiting time  for requests in queue before removing it

**Comment by tevanko** [comment]
Hey @HeeL, thanks for writing about this.  This functionality is now supported in version 1.8.1 of our Node SDK.
